name = "MaterialDecomposition"
uuid = "c27b174a-794e-4afe-9da0-66d3b10781c5"
authors = ["Dale Black <djblack@uci.edu> and contributors"]
version = "1.0.0-DEV"

[deps]
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
Revise = "3"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
